id: A848988D8
title: Brief Turning Back the Summons
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:48.065197
  last_modified_at: 2022-03-01 06:27:48.065202
