id: A848988D8
title: Confession and Fulfilment Insert for Accumulating the Practice of Turning Back
  the Summons of the Ḍākinīs
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:27:48.067034
  last_modified_at: 2022-03-01 06:27:48.067038
